#!/bin/bash -e
#
# Copyright 2016-present The Compute Engine Open Source Dashboard Cluster Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

sudo apt-get install nodejs-legacy npm -y

sudo useradd -mrU graphite-oss-daemon 2> /dev/null || echo "graphite-oss-daemon already exists"

sudo cp $DIR/systemd/graphite-oss-daemon.service /lib/systemd/system/graphite-oss-daemon.service
sudo touch /var/log/graphite-oss-daemon.log
sudo chown graphite-oss-daemon /var/log/graphite-oss-daemon.log
sudo chgrp graphite-oss-daemon /var/log/graphite-oss-daemon.log

if [ ! -d /opt/graphite-oss-daemon ]; then
  sudo mkdir -p /opt
  sudo git clone https://github.com/material-foundation/graphite-oss-daemon.git /opt/graphite-oss-daemon
fi

pushd /opt/graphite-oss-daemon >> /dev/null

sudo git fetch
sudo git checkout origin/stable
sudo npm install

sudo systemctl enable graphite-oss-daemon
sudo systemctl start graphite-oss-daemon
sudo systemctl daemon-reload

popd >> /dev/null
