#!/bin/bash -e
#
# Copyright 2016-present The Compute Engine Open Source Dashboard Cluster Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

sudo apt-get install -y grafana

# Make grafana open to the public and disable sign up.
sudo sed -i -e '/^\[auth.anonymous\]$/,/^\[/ s/^;enabled .*/enabled = true/' /etc/grafana/grafana.ini
sudo sed -i -e '/^\[users\]$/,/^\[/ s/^;allow_sign_up .*/allow_sign_up = false/' /etc/grafana/grafana.ini
sudo sed -i -e '/^\[users\]$/,/^\[/ s/^;allow_org_create .*/allow_org_create = false/' /etc/grafana/grafana.ini

# Enable pie charts
sudo grafana-cli plugins install grafana-piechart-panel

sudo update-rc.d grafana-server defaults 95 10
sudo service grafana-server restart