#!/bin/bash -e
#
# Copyright 2016-present The Compute Engine Open Source Dashboard Cluster Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

confirm() {
  echo "Press RETURN to continue, or ^C to cancel.";
  read -e ignored
}

GIT='git'
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

LTS="Ubuntu 10.04"
ISSUE=`cat /etc/issue`
if [[ $ISSUE != Ubuntu* ]]; then
  echo "This script is intended for use on Ubuntu, but this system appears";
  echo "to be something else. Your results may vary.";
  echo
  confirm
elif [[ `expr match "$ISSUE" "$LTS"` -eq ${#LTS} ]]; then
  GIT='git-core'
fi

echo "OSS DASHBOARD UBUNTU INSTALL SCRIPT";

ROOT=`pwd`
echo "Dashboard will be installed to: ${ROOT}.";

echo "Testing sudo..."
sudo true
if [ $? -ne 0 ]; then
  echo "ERROR: You must be able to sudo to run this script.";
  exit 1;
fi;

echo "Installing dependencies...";
echo

set +x

# -qq No output except for errors
sudo apt-get -qq update

sudo apt-get clean

sudo apt-get install upstart -y

line() {
  echo
  echo "============================================"
  echo "$@"
}

line "Configuring graphite..."
bash $DIR/configure_graphite || exit 1

line "Configuring grafana..."
bash $DIR/configure_grafana || exit 1

line "Configuring graphite-oss-daemon..."
bash $DIR/configure_daemon || exit 1

line "Completed."
